### ISSUE TITLE
[FE] 개설요청상세보기 DT-03-06-01 삭제요청상세보기 DT-03-06-02 구현

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#55]
## Description

- adminService의 api호출부분을 수정하여 DT03-06의 요청 / 신고 / 검수 목록의 개설요청상세보기 ( ViewAdminPage )를 통해 DT-03-06-01 삭제요청상세보기 DT-03-06-02에서도 호출될수 있게 구현

## Tasks

- [ ]  adminService수정 (랜덤으로 데이터가 불러와지는 코드. 결국 ViewAdminPage.jsx에서 랜덤으로 호출된 api가 개설요청상세보기 DT-03-06-01 삭제요청상세보기 DT-03-06-02 에서 다시 랜덤으로 호출되어서 adminService.js api 호출 코드전면수정

**Comment by jooYeonIya** [comment]
#54 에서 수정
